# -*- coding: utf-8 -*-
"""AI4All project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nff49s-ID-zujs_tFo7kcYYwETZoAgcS

#Competitive Threat and Market Share Loss Prediction

##Libraries
"""

pip install --upgrade kagglehub

import kagglehub
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

news_path = kagglehub.dataset_download("miguelaenlle/massive-stock-news-analysis-db-for-nlpbacktests")

print("Path to dataset files:", news_path)

stock_path = kagglehub.dataset_download("ehallmar/daily-historical-stock-prices-1970-2018")

print("Path to dataset files:", stock_path)

"""##Dataset"""

# news headlines
dataset_root = os.path.join(news_path, 'analyst_ratings_processed.csv')
news = pd.read_csv(dataset_root)
news

# historic stock prices
dataset_root = os.path.join(stock_path, 'historical_stock_prices.csv')
stock = pd.read_csv(dataset_root)
stock

"""###Data Cleaning - news headlines"""

# remove "unnameed: 0" column, duplicates as the index

# reuncate "date" info to contain only YYYY-MM-DD, so take out the time

# remove any rows with null values

# remove any rows where the date exceeds date range of stock_df

# remove news_df rows where value in "stock" does not match "ticker" value in stock_df

"""###Data Cleaning - historic stock"""

# remove any rows with null values

# remove any rows where the date exceeds the date range of news_df

# remove stock_df rows where value in "ticker" value does not match "stock" value in news_df

# by matching the dates of news_df to dates of stock_df,
# only keep rows stock_df with dates 3 days from the news headline publish date and also the row for the date after
## ex. news_date(2025-04-23); keep rows from stock_df with dates {2025-04-21,2025-04-22, 2025-04-23, 2025-04-24}

"""##Visualizations"""

# plot the top # most mentioned stock ticker in news_df

# plot the top # most traded stocks in stock_df

# plot the top # stocks with the largest price changes within a day

# plot counts of top bigrams (n-grams)

# other plots you deem fit