# -*- coding: utf-8 -*-
"""AI4All project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nff49s-ID-zujs_tFo7kcYYwETZoAgcS

#Competitive Threat and Market Share Loss Prediction

##Libraries
"""

# if kagglehub not found
!pip install --upgrade kagglehub

import kagglehub
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

news_path = kagglehub.dataset_download("miguelaenlle/massive-stock-news-analysis-db-for-nlpbacktests")

print("Path to dataset files:", news_path)

stock_path = kagglehub.dataset_download("ehallmar/daily-historical-stock-prices-1970-2018")

print("Path to dataset files:", stock_path)

"""##Dataset"""

# news headlines
dataset_root = os.path.join(news_path, 'analyst_ratings_processed.csv')
news = pd.read_csv(dataset_root)
news

# historic stock prices
dataset_root = os.path.join(stock_path, 'historical_stock_prices.csv')
stock = pd.read_csv(dataset_root)
stock

"""###Data Cleaning"""

# remove "unnameed: 0" column from news_df, duplicates as the index

# reuncate "date" info to contain only YYYY-MM-DD from news_df, so take out the time

# remove any rows with null values from news_df

# remove any rows from news_df where the date exceeds date range of stock_df

# remove rows from news_df where value in "stock" does not match "ticker" value in stock_df

# remove any rows with null values from stock_df

# remove any rows from stock_df where the date exceeds the date range of news_df

# remove rows from stock_df where value in "ticker" value does not match "stock" value in news_df

# by matching the dates of news_df to dates of stock_df,
# only keep rows stock_df with dates 3 days from the news headline publish date and also the row for the date after
## ex. news_date(2025-04-23); keep rows from stock_df with dates {2025-04-21,2025-04-22, 2025-04-23, 2025-04-24}

# by matching the date of the news headline and the stock ticker,
# add the prices of the stock from the past 3 days to a new column in news_df
# also add the next day's stock price to the news_df as a new column

# add column in news_df for whether stock prices went up or down
## ex. price from 1_day_ago is higher than price of next_day -> price_went_up column value = 1
## ex. price from 1_day_ago is lower than price of next_day -> price_went_up column value = 0

"""##Visualizations"""

# plot the top # most mentioned stock ticker in news_df

# plot the top # most traded stocks in stock_df

# plot the top # stocks with the largest price changes within a day

# plot counts of top bigrams (n-grams)

# plot price_went_up column

# other plots you deem fit

"""##Data Spliting"""

X = news.drop('price_went_up', axis=1)
y = news['price_went_up']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=6, stratify=True)

"""##Pre-processing"""

